version: '3.8'

services:
  # Servei per a la base de dades
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: aniol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  # Servei per al backend (Node.js)
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_container
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend_network  # Add to backend_network
    environment:
      DB_USER: aniol
      DB_HOST: postgres
      DB_NAME: movies
      DB_PASSWORD: password
      DB_PORT: 5432
      API_KEY: 38744b6c459ddd6f2e5e97a7d598773e

  # Servei per al frontend (React Native)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    ports:
      - "19000:19000"
      - "19001:19001"
    volumes:
      - ./frontend:/app
      - ./frontend/assets:/app/assets:delegated
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
    depends_on:
      - backend
    networks:
      - backend_network  # frontend on the same network as backend

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
