version: "3.8"

services:
  # Base de dades
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: aniol
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  # Backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend_container
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - backend_network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_container
    env_file:
      - ./frontend/.env
    ports:
      - "19000:19000"
      - "19001:19001"
    volumes:
      - ./frontend:/app
      - ./frontend/assets:/app/assets:delegated
    depends_on:
      - backend
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:
    driver: bridge
